# Generated by Django 5.0.3 on 2024-04-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_balance_options_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
