# Generated by Django 5.0.3 on 2024-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('Main', 'Main'), ('Additional', 'Additional')], default='Main', max_length=100),
        ),
    ]
