# Generated by Django 5.0.3 on 2024-04-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_source_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Online Transfer', 'Online Transfer')], default='Card', max_length=100),
        ),
    ]
