# Generated by Django 5.0.3 on 2024-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
