# Generated by Django 5.0.3 on 2024-04-12 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_transaction_date_time_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
